spring:
  application:
    name: client
  kafka:
    bootstrap-servers: http://localhost:9092
  cloud:
    bus:
      destination: payment-prod-event-config-event-json
    config:
      name: payment-client
      fail-fast: true
      retry:
        initial-interval: 1000
        max-attempts: 5
        multiplier: 1.1
      request-connect-timeout: 2000
      request-read-timeout: 10000
  config:
    import: optional:configserver:http://localhost:8888

management:
  endpoints:
    web:
      exposure:
        include: refresh, busrefresh