server:
  port: 8888
spring:
  application:
    name: config-server
  kafka:
    bootstrap-servers: http://localhost:9092
  cloud:
    bus:
      destination: payment-prod-event-config-event-json
    config:
      server:
        git:
          uri: https://github.com/Dev-Payment-System/payment-server
          search-paths: config-file/**
          default-label: develop

management:
  endpoints:
    web:
      exposure:
        include: refresh, busrefresh